/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import Datos.Agendas;
import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author 203pc1
 */
public class VentanaAdministrador extends javax.swing.JFrame {
    private Agendas agenda;
    private pnlAlta palta;
    private pnlModificaciones pnlModifi;
    private int usuarioValidado;
    /**
     * Creates new form VentanAdministrador
     */
    public VentanaAdministrador(Agendas agenda, int usuarioValidado) {
        this.agenda = agenda;
        this.usuarioValidado=usuarioValidado;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        mnuAlta = new javax.swing.JMenuItem();
        mnuBaja = new javax.swing.JMenuItem();
        mnuModificacion = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuDesconectar = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ADMINISTRADOR");
        setMinimumSize(new java.awt.Dimension(100, 100));

        jMenu4.setText("Gestion Usuarios");

        mnuAlta.setText("Alta");
        mnuAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltaActionPerformed(evt);
            }
        });
        jMenu4.add(mnuAlta);

        mnuBaja.setText("Baja");
        jMenu4.add(mnuBaja);

        mnuModificacion.setText("Modificacion");
        mnuModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModificacionActionPerformed(evt);
            }
        });
        jMenu4.add(mnuModificacion);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Salir");

        mnuDesconectar.setText("Desconectar");
        mnuDesconectar.setMaximumSize(new java.awt.Dimension(109, 22));
        mnuDesconectar.setMinimumSize(new java.awt.Dimension(109, 22));
        mnuDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDesconectarActionPerformed(evt);
            }
        });
        jMenu5.add(mnuDesconectar);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDesconectarActionPerformed
        // TODO add your handling code here:
        quitarPaneles();
        new Validacion(agenda).setVisible(true);
        dispose();
        pack();
    }//GEN-LAST:event_mnuDesconectarActionPerformed

    private void mnuAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaActionPerformed
        // TODO add your handling code here:
        quitarPaneles();
        palta=new pnlAlta(agenda);
        this.add(palta, BorderLayout.LINE_START);
        pack();
    }//GEN-LAST:event_mnuAltaActionPerformed

    private void mnuModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModificacionActionPerformed
        // TODO add your handling code here:
        quitarPaneles();
        pnlModifi=new pnlModificaciones(agenda,this);
        this.add(pnlModifi, BorderLayout.CENTER);
        this.pack();
    }//GEN-LAST:event_mnuModificacionActionPerformed

   private void quitarPaneles(){
    try{
        // GUARDAR EMAIL ANTES DE BORRAR PANEL PARA GUARDAR CAMBIOS
        // CON PANELES NO HACE FALTA POR SER UN OBJETO SI ES UN PRIMITIVO SSSIII
       this.agenda = palta.agenda;
       this.remove(palta);
    }catch(Exception e){}
    try{
        // GUARDAR EMAIL ANTES DE BORRAR PANEL PARA GUARDAR CAMBIOS
        // CON PANELES NO HACE FALTA POR SER EMAIL UN OBJETO SI ES UN PRIMITIVO SSII
      this.agenda = pnlModifi.agenda;
       this.remove(pnlModifi);
    }catch(Exception e){}
    
} 
  
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem mnuAlta;
    private javax.swing.JMenuItem mnuBaja;
    private javax.swing.JMenuItem mnuDesconectar;
    private javax.swing.JMenuItem mnuModificacion;
    // End of variables declaration//GEN-END:variables
}
